// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";

export interface IEventFields {
  /** Title */
  title: string;

  /** Note */
  note?: string | undefined;

  /** Date */
  date: string;

  /** Location */
  location: string;

  /** Country */
  country: string;

  /** Url */
  url?: string | undefined;

  /** Tickets URL */
  ticketsUrl?: string | undefined;

  /** Sold out */
  soldOut: boolean;
}

export interface IEvent extends Entry<IEventFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "event";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IFileFields {
  /** Title */
  title: string;

  /** File */
  file: Asset;

  /** Category */
  category: string;

  /** Page */
  page: IPage[];
}

export interface IFile extends Entry<IFileFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "file";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPageFields {
  /** Title */
  title: string;

  /** Slug */
  slug: string;

  /** Description */
  description?: string | undefined;
}

export interface IPage extends Entry<IPageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "page";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ISocialMediaFields {
  /** Title */
  title: string;

  /** Icon */
  icon: string;

  /** URL */
  url: string;

  /** Order */
  order?: number | undefined;
}

export interface ISocialMedia extends Entry<ISocialMediaFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "socialMedia";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IVideoFields {
  /** Title */
  title: string;

  /** Author */
  author: "Roundabouts";

  /** Video */
  video: Asset;
}

export interface IVideo extends Entry<IVideoFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "video";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IWebsiteFields {
  /** Title */
  title: string;

  /** Description */
  description: string;
}

export interface IWebsite extends Entry<IWebsiteFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "website";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "event"
  | "file"
  | "page"
  | "socialMedia"
  | "video"
  | "website";

export type IEntry = IEvent | IFile | IPage | ISocialMedia | IVideo | IWebsite;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
